sc config "AdobeARMservice" start= disabled
sc config "AJRouter" start= disabled
sc config "ALG" start= disabled
sc config "tzautoupdate" start= disabled
sc config "CertPropSvc" start= disabled
sc config "DiagTrack" start= disabled
sc config "diagsvc" start= disabled
sc config "DPS" start= disabled
sc config "WdiServiceHost" start= disabled
sc config "WdiSystemHost" start= disabled
sc config "DialogBlockingService" start= disabled
sc config "TrkWks" start= disabled
sc config "MapsBroker" start= disabled
sc config "Fax" start= disabled
sc config "lfsvc" start= disabled
sc config "iphlpsvc" start= disabled
sc config "AppVClient" start= disabled
sc config "MsKeyboardFilter" start= disabled
sc config "uhssvc" start= disabled
sc config "SmsRouter" start= disabled
sc config "NetTcpPortSharing" start= disabled
sc config "CscService" start= disabled
sc config "ssh-agent" start= disabled
sc config "PhoneSvc" start= disabled
sc config "Spooler" start= disabled
sc config "wercplsupport" start= disabled
sc config "PcaSvc" start= disabled
sc config "RetailDemo" start= disabled
sc config "RemoteAccess" start= disabled
sc config "shpamsvc" start= disabled
sc config "SCardSvr" start= disabled
sc config "ScDeviceEnum" start= disabled
sc config "SCPolicySvc" start= disabled
sc config "lmhosts" start= disabled
sc config "UevAgentService" start= disabled
sc config "VSS" start= disabled
sc config "WerSvc" start= disabled
sc config "stisvc" start= disabled
sc config "wisvc" start= disabled
sc config "MixedRealityOpenXRSvc" start= disabled
sc config "WpnService" start= disabled
sc config "WSearch" start= disabled
sc config "XboxGipSvc" start= disabled
sc config "XblAuthManager" start= disabled
sc config "XblGameSave" start= disabled
sc config "XboxNetApiSvc" start= disabled
sc config "GoogleChromeElevationService" start= disabled
sc config "gupdate" start= disabled
sc config "gupdatem" start= disabled
powercfg -h off
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
sc config "Name of Service" start= disabled
